version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:gaindakot@localhost:5432/taskplatform?schema=public
      PORT: 8000
      JWT_SECRET: #^*@*#(@#(@#jfdlfjdkf))

  frontend:
    build:
      context: ./frontend
    ports:
      - 4173:4173
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gaindakot
      POSTGRES_DB: taskplatform
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
