version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - 4173:4173
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gaindakot
      POSTGRES_DB: taskplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
